### ISSUE TITLE
Add ability to accept changing the speeds via the chat.

### ISSUE THREAD

**Issue by bwookieeeee** [letsRobot/tellyBot#1]
Like how users with auth level 2 can enter `.ser pivot` to enter pivot mode. I tried to do it myself but I don't really understand the `strcmp` command and how to manipulate it. It should either accept both straight and turning speed like `.ser speed straight|turn x` or two separate commands like `.ser speed x` and `.ser tspeed x`.

**Comment by Nocturnal42** [comment]
Where are you getting strcmp from? Have a look at any of the other compound chat command handlers.

**Comment by bwookieeeee** [comment]
https://github.com/letsRobot/tellyBot/blob/master/TriBot.c#L340 here and
https://github.com/letsRobot/tellyBot/blob/master/EyesWS2812.c#L342 for multi word compares.

**Comment by Nocturnal42** [comment]
Sorry. My mistake. I was thinking of the wrong repo. You can’t compare strings directly. Ie string1 == string2 instead you have to use strcmp. It will return 0 if the two strings match and non zero if the don’t. the second one you listed does the same, but only compares x number of characters and not whole strings.

**Comment by reltham** [comment]
So the tribot code only uses one speed (it uses the straight speed for everything). So in that module I just added one command "speed" ( .ser speed 100  to set the speed to 100).  In the standard bot module I added both "speed" and "turnspeed".  These all constrain the value to be 10 to 200.
